---
title: 'Game of Thrones, Text mining, sentiment analysis, and visualization'
author: 'Aske Høj Andersen'
date: '27 march, 2026'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(here)

# For text mining:

library(pdftools)
library(tidytext)
library(textdata) 
library(ggwordcloud)
```

#Get the first book of GoT:
```{r get-document}
GoT <- here("data","got.pdf")
GoT_text <- pdf_text(GoT)
```


```{r single-page}
GoT_p9 <- GoT_text[9]
GoT_p9
```


#Some wrangling:

```{r split-lines}
GoT_df <- data.frame(GoT_text) %>% 
  mutate(text_full = str_split(GoT_text, pattern = '\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full)) 

```


#Get the individual words in tidy format

```{r tokenize}
GoT_tokens <- GoT_df %>% 
  unnest_tokens(word, text_full)

# See how this differs from `ipcc_df`
# Each word has its own row!
```


#Counting the words

```{r count-words}
GoT_wc <- GoT_tokens %>% 
  count(word) %>% 
  arrange(-n)
GoT_wc
```



#Removeing stop words:

```{r stopwords}
GoT_stop <- GoT_tokens %>% 
  anti_join(stop_words) %>% 
  select(-GoT_text)
```

#checking the counts:
```{r count-words2}
GoT_stop <- GoT_tokens %>% 
  anti_join(bind_rows(stop_words, tibble(word = c("chapter","book","page","line","septon","knight","ned","stark","arya","sansa","bran","jon","snow","robb","catelyn","tyrion","cersei","jaime","joffrey","daenerys","dany","drogo","viserys","winterfell","said","say","says","would","could","one","two","back","hand","head","eyes", "i'm"))), by = "word") %>% 
  select(-GoT_text)
```

#Getting rid of the numbers
```{r skip-numbers}
# This code will filter out numbers by asking:
# If you convert to as.numeric, is it NA (meaning those words)?
# If it IS NA (is.na), then keep it (so all words are kept)
# Anything that is converted to a number is removed

GoT_no_numeric <- GoT_stop %>% 
  filter(is.na(as.numeric(word)))
```


#A word cloud of GoT

```{r wordcloud-prep}
# There are 11183 unique words 
length(unique(GoT_no_numeric$word))

# We probably don't want to include them all in a word cloud. Let's filter to only include the top 100 most frequent?
GoT_top100 <- GoT_no_numeric %>% 
  count(word) %>% 
  arrange(-n) %>% 
  head(100)
GoT_top100
```

```{r wordcloud}
GoT_cloud <- ggplot(data = GoT_top100, aes(label = word)) +
  geom_text_wordcloud() +
  theme_minimal()

GoT_cloud
```

That's underwhelming. Let's customize it a bit:
```{r wordcloud-pro}
ggplot(data = GoT_top100, aes(label = word, size = n)) +
  geom_text_wordcloud_area(aes(color = n), shape = "circle") +
  scale_size_area(max_size = 12) +
  scale_color_gradientn(colors = c("red","orange","orange")) +
  theme_minimal()
```

#Sentiment analysis
```{r afinn}
get_sentiments(lexicon = "afinn")
#choose yes!


#positive words:
afinn_pos <- get_sentiments("afinn") %>% 
  filter(value %in% c(3,4,5))

afinn_pos
```

#binary, "positive" or "negative"
```{r bing}
get_sentiments(lexicon = "bing")
```

#NRC
```{r nrc}
get_sentiments(lexicon = "nrc")

```

#Afinn: 

```{r bind-afinn}
GoT_afinn <- GoT_stop %>% 
  inner_join(get_sentiments("afinn"))
GoT_afinn
```

```{r count-afinn}
#Counting afinn
GoT_afinn_hist <- GoT_afinn %>% 
  count(value)

#Plotting: 
ggplot(data = GoT_afinn_hist, aes(x = value, y = n)) +
  geom_col(aes(fill = value)) +
  theme_bw()
```

```{r summarize-afinn}
GoT_summary <- GoT_afinn %>% 
  summarize(
    mean_score = mean(value),
    median_score = median(value)
  )
GoT_summary 
```

# NRC lexicon
```{r bind-bing}
GoT_nrc <- GoT_stop %>% 
  inner_join(get_sentiments("nrc"))
```

```{r check-exclusions}
GoT_exclude <- GoT_stop %>% 
  anti_join(get_sentiments("nrc"))

# Find the most excluded:
GoT_exclude_n <- GoT_exclude %>% 
  count(word, sort = TRUE)

head(GoT_exclude_n)
```

```{r count-bing}
#Finding counts
GoT_nrc_n <- GoT_nrc %>% 
  count(sentiment, sort = TRUE)

#Plotting counts

ggplot(data = GoT_nrc_n, aes(x = sentiment, y = n)) +
  geom_col(aes(fill = sentiment))+
  theme_bw()
```

```{r count-nrc}
#Dividing word by sentiment (emotional response)
GoT_nrc_n5 <- GoT_nrc %>% 
  count(word,sentiment, sort = TRUE) %>% 
  group_by(sentiment) %>% 
  top_n(5) %>% 
  ungroup()

GoT_nrc_gg <- ggplot(data = GoT_nrc_n5, aes(x = reorder(word,n), y = n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, ncol = 2, scales = "free") +
  coord_flip() +
  theme_minimal() +
  labs(x = "Word", y = "count")

# Showing it
GoT_nrc_gg

# Saveing it
ggsave(plot = GoT_nrc_gg, 
       here("figures","GoT_nrc_sentiment.png"), 
       height = 8, 
       width = 5)

```
